apiVersion: v2
appVersion: 5.27.5
dependencies:
- name: media-servarr-base
  repository: file://../..
  version: 0.9.0
description: Movie collection manager for Usenet and BitTorrent users
home: https://github.com/drinkataco/media-servarr/tree/main/charts/radarr
icon: https://github.com/drinkataco/media-servarr/blob/main/charts/radarr/icon.png
keywords:
- film
- movies
- torrent
- bittorrent
- usenet
- manager
- radarr
kubeVersion: '>=1.24.0-0'
maintainers:
- email: git@jo.shw.al
  name: media-servarr
  url: https://github.com/drinkataco/media-servarr/
name: radarr
sources:
- https://github.com/Radarr/Radarr
- https://github.com/linuxserver/docker-radarr
- https://ghcr.io/onedr0p/exportarr
- https://github.com/drinkataco/media-servarr/tree/main/charts/radarr
type: application
version: 0.18.0
