apiVersion: v2
appVersion: v1.41.0
dependencies:
- name: media-servarr-base
  repository: file://../..
  version: 0.9.0
description: Sleek, modern dashboard that puts all of your apps and services at your
  fingertips
home: https://github.com/drinkataco/media-servarr/tree/main/charts/homarr
icon: https://github.com/drinkataco/media-servarr/blob/main/charts/homarr/icon.png
keywords:
- dashboard
- homarr
kubeVersion: '>=1.24.0-0'
maintainers:
- email: git@jo.shw.al
  name: media-servarr
  url: https://github.com/drinkataco/media-servarr/
name: homarr
sources:
- https://github.com/homarr-labs/homarr
- https://github.com/drinkataco/media-servarr/tree/main/charts/homarr
type: application
version: 0.20.0
