{{- if .Values.global.traefik.enabled }}
# This IngressClass is required because the default IngressClass created by the Traefik Helm chart
# uses the release name as a prefix (e.g., "baseline-traefik" instead of just "traefik").
# Many ingress resources expect the IngressClass to be named "traefik", so we create an additional
# IngressClass with that name pointing to the same Traefik controller.
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: traefik
  labels:
    {{- include "baseline.labels" . | nindent 4 }}
  annotations:
    ingressclass.kubernetes.io/is-default-class: "false"
spec:
  controller: traefik.io/ingress-controller
{{- end }}
