{{- define "media-servarr-base.serviceaccount" -}}
{{- if and .Values.serviceAccount .Values.serviceAccount.create -}}
---

apiVersion: 'v1'
kind: 'ServiceAccount'
metadata:
  name: {{ include "media-servarr-base.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "media-servarr-base.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
imagePullSecrets:
  {{- range .Values.serviceAccount.imagePullSecrets }}
  - name: '{{ .name }}'
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
{{- end }}
