{{- if .Values.traefik.enabled }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: local-network-only
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "mediastack.labels" . | nindent 4 }}
spec:
  ipAllowList:
    sourceRange:
      {{- range .Values.traefik.localNetworkOnly.sourceRanges }}
      - {{ . }}
      {{- end }}
---
{{- if .Values.traefik.securityHeaders.enabled }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: security-headers
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "mediastack.labels" . | nindent 4 }}
spec:
  headers:
    {{- with .Values.traefik.securityHeaders }}
    browserXssFilter: {{ .browserXssFilter }}
    contentTypeNosniff: {{ .contentTypeNosniff }}
    forceSTSHeader: {{ .forceSTSHeader }}
    stsIncludeSubdomains: {{ .stsIncludeSubdomains }}
    stsPreload: {{ .stsPreload }}
    stsSeconds: {{ .stsSeconds }}
    {{- if .customFrameOptionsValue }}
    customFrameOptionsValue: {{ .customFrameOptionsValue }}
    {{- end }}
    {{- if .customBrowserXssValue }}
    customBrowserXssValue: {{ .customBrowserXssValue }}
    {{- end }}
    {{- end }}
{{- end }}
{{- end }}
